name: Lines of code

on:
  push:
    branches:
      - ci/*
      - main
      - develop
      - release/*
  pull_request:

jobs:
  tokei:
    name: Tokei
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tokei
        run: |
          curl -L https://github.com/XAMPPRocky/tokei/releases/download/v12.1.2/tokei-x86_64-unknown-linux-musl.tar.gz | tar xz
          sudo install -m755 ./tokei /usr/bin/tokei

      - name: Run tokei
        id: tokei
        run: |
          ./dev-support/bin/lines-of-code
